<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <id>1</id>
  <title>Newly introduced DoS</title>
  <updated>2023-06-04T20:05:49.777042+00:00</updated>
  <author>
    <name>Luke-Jr 2011-09-27 20:08:05</name>
  </author>
  <generator uri="https://lkiesow.github.io/python-feedgen" version="0.9.0">python-feedgen</generator>
  <entry>
    <id>1</id>
    <title>Newly introduced DoS</title>
    <updated>2023-06-04T20:05:49.777042+00:00</updated>
    <link href="https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2011-September/000604.html" rel="alternate"/>
    <summary>In this code snippet, there is a bool function called "AcceptBlock()" that takes in no parameters. Inside this function, there is a map iterator that finds the previous block index. If the iterator does not find the previous block index, a DoS error with a message of "prev block not found" will be returned. The question following the code asks whether or not it is possible for a peer with more blocks than you to trigger this error.</summary>
    <published>2011-09-27T20:08:05+00:00</published>
  </entry>
</feed>
